### ISSUE TITLE
menu's href does not work

### ISSUE THREAD

**Issue by hafeez-syed** [stbaer/m-dropdown#1]
Hi, I am using m-dropdown with Backbone.js. When I click on the menus, its not taking me to the desired href link :(. 

It works when I use it through bacbone's click events and it triggers the event well.

Please help.

Thanks

**Comment by stbaer** [comment]
Hi, I will take a look later today. Could you create a jsfiddle for this?

**Comment by stbaer** [comment]
@feeziman007 - I just made a quick test and hrefs seem to work fine.
Does this only happen if Backbone is included?

**Comment by stbaer** [comment]
@feeziman007 - looks like a backbone specific problem, closing this for now. If you think otherwise or can provide a fiddle / code example that shows the problem please reopen.

**Comment by hafeez-syed** [comment]
thanks and apologies for the late response. this might be backbone issue.
